# Generated by Django 4.2.1 on 2023-06-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
            
        ),
    ]
