# Generated by Django 4.2.1 on 2023-06-06 07:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='product_name', unique=True),
        ),
    ]
