# Generated by Django 4.2.1 on 2023-07-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_banner_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
