# Generated by Django 4.2.1 on 2023-06-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
