# Generated by Django 4.2.1 on 2023-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_profile_phone_alter_profile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(max_length=150),
        ),
    ]
