# Generated by Django 4.2.1 on 2023-07-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
